### ISSUE TITLE
Comments not highlighted correctly

### ISSUE THREAD

**Issue by ian-h-chamberlain** [yy0931/gitconfig-lsp#1]
Hi, just trying out this extension and it's very nice! It looks like it's early in development so I'm not expecting it to work perfectly, but figured I'd file an issue in case you are looking for feedback.

Comments don't seem to work quite as I would expect – it seems like the grammar does not account for them and there appears to be no `comment` token type being generated:

![Screen Shot 2022-01-13 at 12 23 14 PM](https://user-images.githubusercontent.com/11131775/149378650-7351e1fe-f4f0-4f00-a6c0-2246ec6299be.png)

Also, when a comment is found at the beginning of a file, it appears to break highlighting for the whole file:

![Screen Shot 2022-01-13 at 12 24 47 PM](https://user-images.githubusercontent.com/11131775/149378782-3ae64f1b-b0fd-4226-807b-42ce6a5f5d9c.png)

Let me know if there's anything I can to help reproduce or any other cases you'd like me to try. Thanks for what you've already created, the tooltips etc. are already super helpful!

**Comment by yy0931** [comment]
Thank you for reporting this issue. I'll fix it when I have time.

**Comment by ian-h-chamberlain** [comment]
Thanks for the quick fix! Confirmed the new release highlights comments correctly, awesome!
