### ISSUE TITLE
Highlights for brackets in comments

### ISSUE THREAD

**Issue by yttriumz** [yy0931/gitconfig-lsp#10]
Thank you so much for the fantastic work! Not sure if this is an issue or a feature, but brackets in comments are colored. Maybe they should be highlighted in the same style as regular comments?

![image](https://github.com/yy0931/gitconfig-lsp/assets/43232804/311d8099-d15a-45f2-9cf9-f951a857ab76)

**Comment by yy0931** [comment]
It seems bracketPairColorization overrides the coloring done by this extension. I will check if it's possible to fix this issue when I have time.

**Comment by yy0931** [comment]
We need to wait for https://github.com/microsoft/vscode/issues/149552 to be resolved.
