### ISSUE TITLE
Spaces before comment hash are not preserved when doing a format document

### ISSUE THREAD

**Issue by rcdailey** [yy0931/gitconfig-lsp#12]
I have a comment on a single line in my `.gitconfig` like this:

```
[core]
    autocrlf = false # Disable this
```

When I do Format Document, it removes the space to the left of the `#`, so it ends up looking like this:

```
[core]
    autocrlf = false# Disable this
```

My expectation is that the space is preserved.

**Comment by yy0931** [comment]
Thanks for the catch. I've fixed the formatter to not trim the trailing space of lines that have a line comment.
