### ISSUE TITLE
Steps to launch the language server standalone

### ISSUE THREAD

**Issue by MXfive** [yy0931/gitconfig-lsp#15]
Hi @yy0931.

Great project, really convenient and useful.  I had a look through the source, I'm not too familiar with VSCode extensions, but I  was wondering if there is currently a way, or if one could be added to launch the language server outside the context of a VSCode extension?

This would open up your work to be used by many more people in other editors too.

**Comment by yy0931** [comment]
In my shallow understanding, you need to configure your LSP client to do the same thing as what is done in https://github.com/yy0931/gitconfig-lsp/blob/main/src/extension.ts, and each editor requires different configurations. I don't have the motivation to support other editors, but feel free to post pull requests.
