### ISSUE TITLE
Syntax highlighting are mostly not working with "GitHub Sharp Theme"

### ISSUE THREAD

**Issue by soredake** [yy0931/gitconfig-lsp#3]
With github sharp theme:
![github_sharp](https://user-images.githubusercontent.com/5204968/186884850-11e66740-0e9d-42be-948a-59b05a75d22b.png)

With builtin light plus theme:
![builtin_light_plus](https://user-images.githubusercontent.com/5204968/186884896-25b6278f-7036-464c-b3e9-38325b2a2e12.png)

@joaomoreno

**Comment by yy0931** [comment]
Thank you for reporting the issue. I've added the settings described at https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#enablement-of-semantic-highlighting to enable semantic highlighting in all themes.

**Comment by soredake** [comment]
Thanks!
